### ISSUE TITLE
TRANSITION PART IS NOT WORKING 

### ISSUE THREAD

**Issue by Abhinavkar** [Abhinavkar/SITHUB#6]
would YOU ADD TRANSITION PART FOR ME

**Comment by Abhinavkar** [comment]
> would YOU ADD TRANSITION PART FOR ME

IN THE FILE NEW CARD 
CSS IS SAME AS HTML FILE

**Comment by nileshkr17** [comment]
No!!!!!!!!!!!!!,,do it by yourself!
